2023-05-12 09:30:08,092 ERROR: Exception on /add_song [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\_projects\church\app\routes.py", line 142, in add_song
    return render_template('add_song.html', title='Add a song', form=form)
  File "D:\_projects\church\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "D:\_projects\church\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "D:\_projects\church\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\_projects\church\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\_projects\church\app\templates\add_song.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\_projects\church\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\_projects\church\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\_projects\church\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\_projects\church\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\_projects\church\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\_projects\church\app\templates\base.html", line 50, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\_projects\church\app\templates\add_song.html", line 7, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "D:\_projects\church\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'wtf' is undefined
2023-05-12 09:35:25,039 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 10:04:01,148 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 10:26:13,930 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 10:49:53,894 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 10:52:48,920 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 10:52:56,293 ERROR: Exception on /view_song/1 [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\app\routes.py", line 177, in view_song
    html = chopro.get_html()
  File "D:\_projects\church\app\core.py", line 147, in get_html
    self._process(html_style)
  File "D:\_projects\church\app\core.py", line 141, in _process
    line = self._process_chopro_line(line, 'div')
  File "D:\_projects\church\app\core.py", line 187, in _process_chopro_line
    self._process_chopro_line_chords_lyrics(line, html_style)
  File "D:\_projects\church\app\core.py", line 310, in _process_chopro_line_chords_lyrics
    _generate_chords_lyrics_line_html_table()
  File "D:\_projects\church\app\core.py", line 255, in _generate_chords_lyrics_line_html_table
    for i in xrange(len(chords)):
NameError: name 'xrange' is not defined
2023-05-12 11:24:41,497 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 11:24:48,142 ERROR: Exception on /view_song/1 [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\app\routes.py", line 177, in view_song
    html = chopro.get_html()
AttributeError: 'str' object has no attribute 'get_html'
2023-05-12 11:26:30,381 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 11:28:30,136 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 11:50:12,064 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 11:52:42,935 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 11:53:59,916 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 12:01:18,572 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 12:23:19,367 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 12:26:21,814 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 13:42:40,387 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 13:52:39,050 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 14:07:41,386 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 14:07:52,362 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 14:52:35,416 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-12 14:57:21,066 ERROR: Exception on /view_song/1 [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\app\routes.py", line 176, in view_song
    ori_key = keyset[song.key]
TypeError: tuple indices must be integers or slices, not NoneType
2023-05-12 14:57:23,399 ERROR: Exception on /view_song/1 [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\app\routes.py", line 176, in view_song
    ori_key = keyset[song.key]
TypeError: tuple indices must be integers or slices, not NoneType
2023-05-12 14:58:09,438 ERROR: Exception on /view_song/1 [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\app\routes.py", line 185, in view_song
    html = Chordpro_html(lyrics, key = ori_key)
TypeError: Chordpro_html() got an unexpected keyword argument 'key'
2023-05-12 15:17:29,765 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
